// File name: make24.cpp  (rename this file to make24.cpp before submitting)
// Name:
// Email:
//
// P3 — Make 24, Task C: All-Expressions Solver
//
// Implement the three functions marked TODO below: both make24() overloads
// and arithmetic(). The main() test harness is already written; do not
// modify it.
//
// Task C returns EVERY distinct expression the required search algorithm
// finds, instead of just one. Unlike Task B, Task C IS graded on
// exhaustiveness: the autograder checks your result against the exact set
// the required algorithm produces for each hand -- not just "some correct
// subset." See Section 7 of the project handout.
//
// IMPORTANT:
// "All solutions" means all distinct expression strings generated by the
// algorithm specified in the project handout. Follow arithmetic() exactly:
// generate one addition result and one multiplication result; do NOT add
// the commutative duplicates ev2+ev1 or ev2*ev1. Task C's contract is
// stricter than Task B's: Task B accepts any one valid solution, but Task C
// must produce the complete required set, built the required way.
//
// The autograder treats an expression with or without one extra pair of
// outermost parentheses as the same solution. You do not need to simplify
// or prettify the expression strings before returning them.
//
// This file's own main() only checks the COUNT of expressions you find
// (against a known-correct count for a few small hands) and that your
// result contains no duplicate strings. Matching the count and having no
// duplicates is necessary but NOT sufficient for full credit -- the
// autograder also checks that the actual expressions are the right ones.
//
// Compile:
//   g++ -std=c++17 -Wall -Wextra -o make24 make24.cpp
//
// Run:
//   ./make24

#include <iostream>
#include <vector>
#include <string>
#include <cmath>
#include <exception>
#include <utility>

const double DELTA = 1e-6;
const int GOAL = 24;

// Pairs a running sub-expression's text with its numeric value, so that
// once you find a hand that reduces to a single value equal to GOAL, its
// paired expression string is one answer.
//
// Do not change the name of this struct or its field names, order, or
// types. The autograder uses this exact interface when testing
// arithmetic().
struct Expression_Value {
  std::string expression;
  double value;
};

// Returns every distinct expression string that evaluates to 24 using
// every number in numsVec exactly once, or an empty vector if none exist.
std::vector<std::string> make24(std::vector<double> numsVec);

// Accumulator overload: appends every solution expression found while
// searching ev_vec onto solutions (skipping exact-duplicate strings).
// Unlike Task B's make24(), this returns nothing -- it must keep searching
// every remaining pair and candidate after finding a solution, instead of
// stopping at the first one, so that every distinct expression gets a
// chance to be found.
void make24(std::vector<Expression_Value> ev_vec, std::vector<std::string>& solutions);

std::vector<Expression_Value> arithmetic(Expression_Value ev1, Expression_Value ev2);
void print(const std::vector<double>& numsVec);

// Returns true iff str already appears in vec. You are not required to
// modify this function.
bool contains(const std::vector<std::string>& vec, const std::string& str) {
  for (int i = 0; i < static_cast<int>(vec.size()); i++) {
    if (vec[i] == str) {
      return true;
    }
  }
  return false;
}

// ── Helper for main() ─────────────────────────────────────────────────────
static void print_result(int passed, int total) {
  if (passed == total)
    std::cout << "All " << total << " tests passed.\n";
  else
    std::cout << passed << "/" << total << " tests passed.\n";
}

// ── main() — do not modify ────────────────────────────────────────────────
// expectedCount below is the true number of distinct expressions the
// required algorithm finds for each hand (independently verified, not
// something you need to take on faith). The Gradescope autograder checks
// additional hands you have not seen here (including some five-number
// hands) and, for every hand, checks the ACTUAL expressions returned, not
// just their count -- so passing every test below is necessary but far
// from sufficient for full credit.
int main() {
  struct TestCase { std::vector<double> data; int expectedCount; const char* label; };
  std::vector<TestCase> tests = {
    {{24},          1,  "{24}"},
    {{1},           0,  "{1}"},
    {{12, 4, 2},    6,  "{12,4,2}"},
    {{1, 2, 4},     0,  "{1,2,4}"},
    {{1, 1, 1},     0,  "{1,1,1}"},
    {{1, 2, 3, 4}, 61,  "{1,2,3,4}"},
    {{4, 4, 7, 7},  1,  "{4,4,7,7}"},
    {{1, 2, 2, 2},  0,  "{1,2,2,2}"},
  };

  int pass = 0;
  auto chk = [&](const TestCase& t) {
    try {
      std::vector<std::string> got = make24(t.data);

      // No-duplicates self-check: every returned string should be unique.
      std::vector<std::string> seen;
      for (const std::string& s : got) {
        if (contains(seen, s)) {
          std::cout << "FAIL: make24(" << t.label << ") returned a duplicate expression: \""
                    << s << "\"\n";
          return;
        }
        seen.push_back(s);
      }

      if (static_cast<int>(got.size()) == t.expectedCount) {
        pass++;
        return;
      }
      std::cout << "FAIL: make24(" << t.label << ") expected " << t.expectedCount
                << " distinct expression(s), got " << got.size() << "\n";
    } catch (const std::exception& e) {
      std::cout << "FAIL: make24(" << t.label << ") threw unexpectedly: "
                << e.what() << "\n";
    }
  };

  for (const TestCase& t : tests) chk(t);
  print_result(pass, static_cast<int>(tests.size()));
  return 0;
}

// ════════════════════════════════════════════════════════════════════════
//  IMPLEMENT make24(vector<double>) BELOW
// ════════════════════════════════════════════════════════════════════════
//
// Same wrapper pattern as Task B: convert each number in numsVec into a
// "trivial" Expression_Value (its expression is just its own literal value
// as a string; its value is itself), collect those into a vector, and
// delegate to the make24(vector<Expression_Value>, vector<string>&)
// overload below, passing an initially-empty solutions vector. Return that
// vector once the search finishes.
//
// You may assume every entry of numsVec is an integer value and that
// numsVec contains at least one number.
//
// Hint: std::to_string(static_cast<int>(x)) turns a whole-number double x
// into the text you want for its starting expression.
std::vector<std::string> make24(std::vector<double> numsVec) {
  // TODO
  return {};  // placeholder -- remove this line when you implement the above
}

// ════════════════════════════════════════════════════════════════════════
//  IMPLEMENT make24(vector<Expression_Value>, vector<string>&) BELOW
// ════════════════════════════════════════════════════════════════════════
//
// Appends every distinct solution expression found while searching ev_vec
// onto solutions. See Section 2 of the project handout for the full
// recursive definition and a worked example trace; the pair-traversal
// structure is identical to Task A/B's make24(). The key difference from
// Task B is that this function returns nothing and never stops early --
// after finding a solution it must keep exploring every remaining pair and
// candidate, because a different pair or a different candidate value may
// lead to a different, equally valid expression that also needs to be
// collected.
//
// Base case (size == 1):
//   If the one remaining value is (approximately -- see the DELTA
//   discussion in Section 3 of the handout) equal to GOAL, its expression
//   is a solution -- append it to solutions, UNLESS an identical string is
//   already present (use contains(), given above). Duplicate expression
//   strings for the same hand can and do arise: different (i, j) pairs, or
//   different orders of combining the same values, sometimes reduce to
//   the exact same expression text, especially when the input has
//   repeated values. Either way, this function returns nothing -- there is
//   no more recursing to do once size == 1.
//
// Recursive case (size >= 2):
//   Consider every pair of positions (i, j) with i < j. For each pair,
//   arithmetic() (also below -- its own TODO) gives every way of combining
//   ev_vec[i] and ev_vec[j] into a single Expression_Value. For each
//   candidate, build a smaller hand by removing positions i and j and
//   appending the candidate, then recurse on that smaller hand -- every
//   time, for every pair and every candidate, regardless of what earlier
//   recursive calls already added to solutions.
//
// ┌─ GOTCHA ──────────────────────────────────────────────────────────────┐
// │  Removing two selected elements by swap() + pop_back() is easy to    │
// │  get subtly wrong. A swap used to remove one selected element may    │
// │  change what value is stored at the other selected index.            │
// │                                                                      │
// │  Since i < j, remove the element at the LARGER index j first.        │
// │  Doing so does not disturb the element at index i. After j has been  │
// │  removed, remove i. Section 2 of the handout works through a full    │
// │  counterexample.                                                     │
// │                                                                      │
// │  Remember: after removing j, cloneVec has size - 1 elements, so its  │
// │  last valid index is size - 2 -- not size - 1.                       │
// └─────────────────────────────────────────────────────────────────────┘
void make24(std::vector<Expression_Value> ev_vec, std::vector<std::string>& solutions) {
  // TODO
}

// ── IMPLEMENT arithmetic() BELOW ──────────────────────────────────────────
//
// Returns every well-defined result of combining ev1 and ev2 with +, -, *,
// and /, as Expression_Value objects: each result pairs the computed
// numeric value with the corresponding combined expression string.
//
// Build each expression string as "(" + left + op + right + ")" -- always
// keep the parentheses, even though it looks redundant for a single pair
// right now. Once these results get combined again in a later recursive
// call, the parentheses are what keep the precedence correct (compare
// 5/(2*3) with the wrong, unparenthesized 5/2*3).
//
// Addition and multiplication are commutative, so each needs only one
// entry. Subtraction and division are NOT commutative, so both orders
// matter and both must be included: ev1.value - ev2.value as well as
// ev2.value - ev1.value, and likewise for division. A division is only
// well-defined when its divisor is nonzero -- guard each division
// separately (skip it rather than computing it) when the relevant value
// is within DELTA of zero, exactly as in Task A's arithmetic().
//
// A call with two ordinary nonzero operands should return six results, in
// this order (values shown; build the matching expression string for
// each): ev1+ev2, ev1-ev2, ev2-ev1, ev1*ev2, ev1/ev2, ev2/ev1.
//
// IMPORTANT FOR TASK C:
// Follow this arithmetic() construction exactly. Generate only one
// addition result and one multiplication result. Do NOT also generate
// ev2+ev1 or ev2*ev1. Task C is graded against the exact expression set
// produced by the algorithm specified in the project handout.
std::vector<Expression_Value> arithmetic(Expression_Value ev1, Expression_Value ev2) {
  // TODO
  return {};  // placeholder -- remove this line when you implement the above
}

// Prints the elements of numsVec on one line, space-separated. Handy for
// tracing your own recursion while debugging; not used by main().
void print(const std::vector<double>& numsVec) {
  for (int i = 0; i < static_cast<int>(numsVec.size()); ++i) {
    std::cout << numsVec[i] << " ";
  }
  std::cout << std::endl;
}
